language: java
jdk:
  - oraclejdk8
script: mvn -fmain/pom.xml clean package
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7d429ab35361726e26f2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
