language: java
jdk:
- oraclejdk8
before_install: "curl -L --cookie 'oraclelicense=accept-securebackup-cookie;'  http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip -o /tmp/policy.zip && sudo unzip -j -o /tmp/policy.zip *.jar -d `jdk_switcher home oraclejdk8`/jre/lib/security && rm /tmp/policy.zip"
script: mvn -fmain/pom.xml -Puber-jar clean package
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7d429ab35361726e26f2
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: releases
  draft: true
  api_key:
    secure: ZjE1j93v3qbPIe2YbmhS319aCbMdLQw0HuymmluTurxXsZtn9D4t2+eTr99vBVxGRuB5lzzGezPR5zjk5W7iHF7xhwrawXrFzr2rPJWzWFt0aM+Ry2njU1ROTGGXGTbv4anWeBlgMxLEInTAy/9ytOGNJlec83yc0THpOY2wxnk=
  file: main/uber-jar/target/Cryptomator-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    repo: cryptomator/cryptomator
    tags: true
