language: java
jdk:
- oraclejdk8
script: mvn -fmain/pom.xml clean package
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7d429ab35361726e26f2
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: releases
  api_key:
    secure: ZjE1j93v3qbPIe2YbmhS319aCbMdLQw0HuymmluTurxXsZtn9D4t2+eTr99vBVxGRuB5lzzGezPR5zjk5W7iHF7xhwrawXrFzr2rPJWzWFt0aM+Ry2njU1ROTGGXGTbv4anWeBlgMxLEInTAy/9ytOGNJlec83yc0THpOY2wxnk=
  file: main/ui/target/dist/Cryptomator.jar
  skip_cleanup: true
  on:
    repo: cryptomator/cryptomator
    tags: true
